### ISSUE TITLE
Convert Casalini recs using BF2 converter

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/ld4p#33]
Create script that VM can run to convert our 36K Casalini records using the LoC BF2 converter

**Comment by dazza-codes** [comment]
This has been done using the ld4p-tracer-bullet-scripts repo and running the conversions on farmshare.  Additional work is now in progress to transfer the solution into the component repo, i.e. https://github.com/sul-dlss/ld4p-marcxml-to-bibframe2 and to run the conversions on the converter-dev box.

**Comment by dazza-codes** [comment]
This is blocked by decisions about data directories and enabling file IO on the converter-dev box.  See:
- https://github.com/sul-dlss/ld4p-marcxml-to-bibframe2/issues/6
- slack commentary at https://sul-dlss.slack.com/archives/ld4p-dev/p1488938474000075

**Comment by dazza-codes** [comment]
We resolved some blocks by deciding to use somewhat arbitrary directory structure, for now.  This resulted in creating a couple of new shared_configs repos and modification to the converter code deployment to use these config data.  Some issues on this need to be discussed later, which might be done in https://github.com/sul-dlss/operations-tasks/issues/330

The MARC21 to MARC-XML conversion code will build and run, but the converter-dev box cannot connect to the Auth-DB system to resolve authority URIs.  Tony will fix this over the weekend, see https://github.com/sul-dlss/operations-tasks/issues/332

The XML -> RDF batch process is now running on the converter-dev box.  It converts, in serial fashion, approx. 3-to-6 records/sec.  It runs well within the bounds of the converter-dev capacity - seems that the XSLT is probably single-threaded process and it’s not memory intensive while processing one record at a time (uses approx. 1Gb of RAM out of the 4Gb available, so no swapping).  Mostly CPU and file IO bound.

Although there are some details to iron out, they can be addressed in other issues.  Work on this issue is effectively complete now, but I'm not going to close this myself in case there are questions about it.
