### ISSUE TITLE
Is the BF2 converter creating unique instances?

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/ld4p#69]
Run the following query on http://sul-ld4p-blazegraph-dev.stanford.edu/blazegraph/#query
```sparql
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
SELECT DISTINCT ?i ?item ?agent ?label 
WHERE {
          ?i bf:instanceOf ?work ;
             bf:hasItem ?item .
          ?work bf:contribution ?contribution .
          ?contribution bf:agent ?agent .
          ?agent rdfs:label ?label .
}
ORDER BY ?i
```

Example response data:
- `<http://ld4p-test.stanford.edu/10083896#Instance>`
  - `<http://ld4p-test.stanford.edu/10083896#Item050-9>`
  - `<http://ld4p-test.stanford.edu/10083896#Agent700-17>`
  - `<http://ld4p-test.stanford.edu/10083896#Agent700-18>`
- `<http://ld4p-test.stanford.edu/10083896#Instance856-25>`
  - `<http://ld4p-test.stanford.edu/10083896#Item856-25>`
  - `<http://ld4p-test.stanford.edu/10083896#Agent700-17>`
  - `<http://ld4p-test.stanford.edu/10083896#Agent700-18>`

It returns a lot of URIs for instances like:
- `<http://ld4p-test.stanford.edu/10083896#Instance>`
- `<http://ld4p-test.stanford.edu/10083896#Instance856-25>`

Both of these instance URIs are linked to the same `bf:Agent` URIs.   But, they are linked to different `bf:Item` URIs.  It seems, possibly, that they only differ on this `bf:Item` link.  Could it be that the BF2 converter is creating a new instance for every item, when it _should_ be linking a unique instance to _all_ the items?

That is, there seems to be a general pattern for every instance to be "duplicated" in two forms:
- `<http://ld4p-test.stanford.edu/{catKey}#Instance>`
- `<http://ld4p-test.stanford.edu/{catKey}#Instance{marcField}>`

Click on an instance URIs in blazegraph-dev to "explore" it.  It looks like there is much less data for the `{catKey}#Instance{marcField}` instance than the `{catKey}#Instance`.  Is it possible that these two URIs are actually the same instance?  How or why are they different?

This question has implications for how the data is indexed.  The index approach iterates on all the instances.

**Comment by arcadiafalcone** [comment]
This is expected behavior based on the way the MARC is structured. The Instance#856-25 derives from an 856 field with second indicator 1, representing a link to another version of the resource. In this case the 856 links to a PDF of the table of contents, which is a part of an inferred electronic Instance of the print Instance represented by the URI without the hash. Both print and electronic versions are Instances of the same Work, and so have the same Agents associated with them.

(There's an added complication that in some cases what is linked in the 856 with second indicator 1 may actually be another Work, but that's not what's happening here.)

**Comment by dazza-codes** [comment]
@arcadiafalcone's analysis indicates the BF2 converter is creating instances correctly.
