### ISSUE TITLE
Do we need inferencing?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/ld4p#71]
See #16 for some analysis on inferencing for titles

**Comment by dazza-codes** [comment]
The BF2 triples from the converter often contain redundant triples that enumerate the class hierarchy.  As such, no inference is required.  A complete analysis of these redundant triples has not been done to identify whether all the class and property hierarchies are explicit for each entity.  To be sure, enabling inference is preferred, along with adding the relevant ontologies and vocabularies to the graph.  When adding the ontologies and vocabularies, it is better to do so when the graph is empty or to find a way to do so while temporarily disabiling inference or truth maintenance, otherwise the graph loader could take a long time or possibly fail.  One problem with inferences on BF2 data is that the BF2 ontology uses MADS-RDF and it is an OWL-Full ontology, which means that some inferences cannot be resolved or cannot be resolved efficiently.  It would be better if BF2 were an OWL-EL ontology (which it might be if it did not use MADS-RDF).
